// Code generated by 'yaegi extract maps'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"reflect"
)

func init() {
	Symbols["maps/maps"] = map[string]reflect.Value{}
}
