#!/usr/bin/env node
/*
 * Bundle the compile-service service worker.
 *
 * Reads src/service-worker/compile-cache.ts (which imports the
 * language registry + hash helper from src/lib/compile-service/)
 * and emits public/sw-compile-cache.js — a single classic-format
 * SW file Astro then ships verbatim.
 *
 * Wired into pnpm via a `prebuild` script in package.json so a
 * fresh `pnpm build` always produces an up-to-date SW. Run by hand
 * via `pnpm sw:build` if you change the SW or the normalizer.
 *
 * No esbuild npm package is declared because it's a transitive of
 * vite — we invoke the pinned binary directly to avoid adding a
 * top-level dependency.
 */

import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

await build({
  entryPoints: [resolve(root, "src/service-worker/compile-cache.ts")],
  bundle: true,
  format: "iife",
  target: "es2022",
  platform: "browser",
  /* Service workers can run as ES modules in modern browsers, but
   * IIFE is the safer default — it works in every browser the
   * rest of typeover supports. */
  outfile: resolve(root, "public/sw-compile-cache.js"),
  /* Map the ~ alias the rest of the codebase uses for src/-relative
   * imports. tsconfig.json defines the same mapping for the editor /
   * type-checker side. */
  alias: { "~": resolve(root, "src") },
  /* Strip dead-code paths and minify. The SW runs on every page
   * load, so size matters. */
  minify: true,
  legalComments: "none",
  banner: {
    js:
      "/* typeover compile-service SW. Generated by scripts/build-sw.mjs " +
      "— edit the TS source under src/service-worker/, not this file. */",
  },
});

console.log("✓ built public/sw-compile-cache.js");
