#!/usr/bin/env node
/*
 * Bundle the Vercel Function handlers under src/api/.
 *
 * For each `*.ts` under src/api/, emits a self-contained `.mjs` at
 * the mirrored path under `/api/` at the project root. Vercel auto-
 * detects top-level `/api/*.mjs` as Serverless Functions — because
 * the file is already bundled JS, Vercel never invokes `tsc` on
 * the source and the `moduleResolution: nodenext` extension-
 * policing that broke a raw-TS deploy doesn't apply.
 *
 * Why this lives in scripts/ and not in the Astro build pipeline:
 * Astro's `output: "static"` doesn't know about Functions. Bundling
 * here keeps the static site as-is and gives Vercel exactly the
 * artifact shape its zero-config Function detection wants.
 *
 * Mirrors scripts/build-sw.mjs in shape. Wired into `pnpm build`
 * via the `prebuild` script in package.json so a fresh build always
 * produces up-to-date Function bundles.
 *
 * Per design-docs/32.
 */

import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, relative, resolve } from "node:path";
import { mkdir, readdir, stat } from "node:fs/promises";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const srcRoot = resolve(root, "src/api");
const outRoot = resolve(root, "api");

/** Recursively collect every `.ts` file under src/api/ that isn't
 *  a test. Tests live alongside the source but are vitest-only;
 *  Vercel never sees them. */
async function collectEntries(dir) {
  const out = [];
  for (const item of await readdir(dir, { withFileTypes: true })) {
    const full = resolve(dir, item.name);
    if (item.isDirectory()) {
      out.push(...(await collectEntries(full)));
      continue;
    }
    if (!item.name.endsWith(".ts")) continue;
    if (item.name.endsWith(".test.ts") || item.name.endsWith(".spec.ts")) continue;
    out.push(full);
  }
  return out;
}

async function exists(path) {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

if (!(await exists(srcRoot))) {
  console.log(`[build-api] no src/api/ directory — nothing to bundle`);
  process.exit(0);
}

const entries = await collectEntries(srcRoot);
if (entries.length === 0) {
  console.log(`[build-api] no .ts handlers under src/api/`);
  process.exit(0);
}

await mkdir(outRoot, { recursive: true });

for (const entry of entries) {
  const rel = relative(srcRoot, entry);
  const outFile = resolve(outRoot, rel.replace(/\.ts$/, ".mjs"));
  await mkdir(dirname(outFile), { recursive: true });
  await build({
    entryPoints: [entry],
    bundle: true,
    format: "esm",
    target: "node24",
    platform: "node",
    outfile: outFile,
    /* Keep node built-ins as externals — they resolve at runtime. */
    external: ["node:*", "@vercel/sandbox"],
    /* Mirror the `~/*` alias the rest of the codebase uses. The
     * Function source files import from `~/lib/...` via this
     * alias; esbuild needs the same resolution. */
    alias: { "~": resolve(root, "src") },
    /* Functions are small; minify modestly for size + readability
     * when debugging from the Vercel dashboard log. */
    minify: false,
    legalComments: "none",
    banner: {
      js:
        "/* typeover Vercel Function. Generated by scripts/build-api.mjs " +
        "— edit the TS source under src/api/, not this file. */",
    },
  });
  console.log(`  + ${relative(root, outFile)}`);
}

console.log(`[build-api] bundled ${entries.length} handler(s)`);
