/*
 * Exercise stub templates for `pnpm content:new theme`.
 *
 * Split out of scripts/content-new-theme.ts so the orchestration
 * (argv parsing, slug resolution, preconditions, prompts, stamping)
 * stays separable from the curriculum-shaped YAML scaffolds. When
 * a new exercise `type` lands in the schema, the addition touches
 * this file alone — and any future snapshot test asserting "the
 * stubs look like X" has a clean target.
 *
 * The four stub builders + `SLOT_BUILDERS` array follow design-
 * docs/02's canonical 3-MCQ / 2-fill-word / 2-fill-line / 2-freeform
 * progression. Each builder closes over the slug so it can stamp
 * the correct `themeId` field in its yaml.
 */

export interface Slug {
  lang: string;
  moduleSlug: string;
  themeSlugTail: string;
  moduleId: string;
  themeSlug: string;
  modulePath: string;
  themeYamlPath: string;
  exercisesDir: string;
}

export interface ThemeFields {
  title: string;
  order: number;
  intro: string;
  prerequisites: readonly string[];
}

/** YAML-safe string. Single-line, double-quoted when needed. */
export function yamlStr(s: string): string {
  if (/^[a-zA-Z0-9 _\-./]+$/.test(s)) return s;
  return JSON.stringify(s);
}

export function composeThemeYaml(slug: Slug, fields: ThemeFields): string {
  return `target: ${slug.lang}
moduleId: ${slug.moduleId}
title: ${yamlStr(fields.title)}
order: ${fields.order}
prerequisites: ${fields.prerequisites.length === 0 ? "[]" : `[${fields.prerequisites.map(yamlStr).join(", ")}]`}
intro: |
${fields.intro
  .split("\n")
  .map((l) => `  ${l}`)
  .join("\n")}
`;
}

// MCQ stub (slots 1-3). Template generator with one var pool, three
// distractors. References to ${name} keep the schema's placeholder-
// declared refinement happy and remind the author of the shape.
export function mcqStub(slug: Slug, slot: number): string {
  return `target: ${slug.lang}
themeId: ${slug.themeSlug}
type: mcq
order: ${slot}
prompt: |
  TODO: recognition prompt. What pattern does this exercise
  introduce? Frame it as a TS → Go translation choice.
generator:
  kind: template
  vars:
    name: [TODO_value]
  ts: |-
    TODO: TS snippet with \${name}.
  canonical: |-
    TODO: Go canonical with \${name}.
  distractors:
    - "TODO: wrong-shape #1 with \${name}"
    - "TODO: wrong-shape #2 with \${name}"
    - "TODO: wrong-shape #3 with \${name}"
hints:
  - "TODO layer 1 — observational hint."
  - "TODO layer 2 — pointed hint."
  - "TODO layer 3 — the answer."
runtime: none
notes: |
  Stub generated by \`pnpm content:new theme ${slug.themeSlug}\`.
  Replace TODO markers; keep the slot 1-3 MCQ shape (recognition
  before production). See design-docs/02 for the pedagogy contract.
`;
}

export function fillWordStub(slug: Slug, slot: number): string {
  return `target: ${slug.lang}
themeId: ${slug.themeSlug}
type: fill-word
order: ${slot}
prompt: |
  TODO: production prompt. Which word(s) complete the Go form?
generator:
  kind: template
  vars:
    name: [TODO_name]
    blank_var: [TODO_value]
  ts: |-
    TODO: TS source with \${name}.
  canonical: |-
    TODO: Go canonical with \${name} \${blank_var}
blanks: [blank_var]
hints:
  - "TODO layer 1 — observational hint."
  - "TODO layer 2 — pointed hint."
  - "TODO layer 3 — the answer."
runtime: none
notes: |
  Stub generated by \`pnpm content:new theme ${slug.themeSlug}\`.
  See design-docs/02 — fill-word drills mechanics of syntax.
`;
}

export function fillLineStub(slug: Slug, slot: number): string {
  return `target: ${slug.lang}
themeId: ${slug.themeSlug}
type: fill-line
order: ${slot}
prompt: |
  TODO: production prompt. Type the Go line that completes the
  scaffold to produce the expected output.
generator:
  kind: template
  vars:
    line:
      - 'fmt.Print("")'
  ts: |-
    TODO: TS snippet.
  canonical: |-
    package main

    import "fmt"

    func main() {
    \t\${line}
    }
  distractors:
    - "TODO: wrong-shape #1"
    - "TODO: wrong-shape #2"
expectStdout: |2

runtime: yaegi
blanks: [line]
hints:
  - "TODO layer 1 — observational hint."
  - "TODO layer 2 — pointed hint."
  - "TODO layer 3 — the answer."
notes: |
  Stub generated by \`pnpm content:new theme ${slug.themeSlug}\`. The
  canonical placeholder is \`fmt.Println()\` which prints a blank
  line — replace with the real exercise content, including a
  meaningful expectStdout. \`pnpm runtime:verify\` passes on the
  stub as-is.
`;
}

export function freeformStub(slug: Slug, slot: number): string {
  return `target: ${slug.lang}
themeId: ${slug.themeSlug}
type: freeform
order: ${slot}
prompt: |
  TODO: open prompt. What program should the learner produce?
generator:
  kind: template
  vars: {}
  ts: |-
    TODO: TS source the learner is translating.
  canonical: |-
    package main

    func main() {}
expectStdout: |2

runtime: yaegi
hints:
  - "TODO layer 1 — observational hint."
  - "TODO layer 2 — pointed hint."
  - "TODO layer 3 — the answer (canonical Go program)."
notes: |
  Stub generated by \`pnpm content:new theme ${slug.themeSlug}\`. The
  canonical is a no-op program that produces empty stdout — replace
  with the real exercise content, including a meaningful canonical
  and expectStdout. \`pnpm runtime:verify\` passes on the stub.
`;
}

/** Canonical 3-MCQ / 2-fill-word / 2-fill-line / 2-freeform
 *  progression from design-docs/02. Each entry is a builder closing
 *  over the slug so it knows its own themeId. */
export const SLOT_BUILDERS: ReadonlyArray<(slug: Slug, slot: number) => string> = [
  mcqStub,
  mcqStub,
  mcqStub,
  fillWordStub,
  fillWordStub,
  fillLineStub,
  fillLineStub,
  freeformStub,
  freeformStub,
];
