/*
 * Go dotted-prefix → member names.
 *
 * Covers the stdlib packages the Go curriculum's exercises touch:
 * `fmt`, `strings`, `strconv`, `slices`, `maps`, `errors`, `sort`,
 * `sync`, `time`, `os`, `io`, `bytes`, `regexp`, `bufio`. Builder-
 * method entries for `strings.Builder` and `bytes.Buffer`.
 */

export const GO_MEMBERS: Record<string, readonly string[]> = {
  fmt: [
    "Println",
    "Print",
    "Printf",
    "Sprintln",
    "Sprint",
    "Sprintf",
    "Errorf",
    "Fprintln",
    "Fprint",
    "Fprintf",
    "Scan",
    "Scanln",
    "Scanf",
  ],
  strings: [
    "Contains",
    "ContainsAny",
    "HasPrefix",
    "HasSuffix",
    "Index",
    "LastIndex",
    "Join",
    "Split",
    "SplitN",
    "Replace",
    "ReplaceAll",
    "ToLower",
    "ToUpper",
    "ToTitle",
    "TrimSpace",
    "Trim",
    "TrimLeft",
    "TrimRight",
    "TrimPrefix",
    "TrimSuffix",
    "Repeat",
    "Count",
    "EqualFold",
    "Fields",
    "Builder",
    "NewReader",
    "NewReplacer",
    "Map",
    "Cut",
  ],
  strconv: [
    "Atoi",
    "Itoa",
    "ParseInt",
    "ParseFloat",
    "ParseBool",
    "FormatInt",
    "FormatFloat",
    "FormatBool",
    "Quote",
    "Unquote",
  ],
  slices: [
    "Contains",
    "ContainsFunc",
    "Index",
    "IndexFunc",
    "Sort",
    "SortFunc",
    "SortStableFunc",
    "Reverse",
    "Equal",
    "EqualFunc",
    "Compact",
    "Delete",
    "DeleteFunc",
    "Insert",
    "Concat",
    "Clone",
    "Min",
    "Max",
    "BinarySearch",
  ],
  maps: ["Keys", "Values", "Equal", "EqualFunc", "Copy", "Clone", "DeleteFunc"],
  errors: ["New", "Is", "As", "Unwrap", "Join"],
  sort: [
    "Slice",
    "SliceStable",
    "Ints",
    "Strings",
    "Float64s",
    "Sort",
    "Stable",
    "Search",
    "SearchInts",
    "SearchStrings",
    "Reverse",
  ],
  sync: ["Mutex", "RWMutex", "WaitGroup", "Once", "Map", "Cond", "Pool"],
  time: [
    "Now",
    "Sleep",
    "Since",
    "Until",
    "Date",
    "Parse",
    "Duration",
    "Second",
    "Millisecond",
    "Microsecond",
    "Nanosecond",
    "Minute",
    "Hour",
    "Time",
    "After",
    "Tick",
  ],
  os: [
    "Args",
    "Getenv",
    "Setenv",
    "Exit",
    "Stdout",
    "Stderr",
    "Stdin",
    "Open",
    "Create",
    "ReadFile",
    "WriteFile",
    "Getwd",
  ],
  io: ["Copy", "EOF", "Reader", "Writer", "Closer", "ReadAll"],
  bytes: [
    "Buffer",
    "Equal",
    "Contains",
    "Index",
    "Split",
    "Join",
    "ToLower",
    "ToUpper",
    "NewReader",
  ],
  regexp: ["Compile", "MustCompile", "MatchString", "Match"],
  bufio: ["NewReader", "NewWriter", "NewScanner", "Scanner"],

  /* Common builder / buffer types' methods. */
  "strings.Builder": ["WriteString", "WriteByte", "WriteRune", "String", "Len", "Reset"],
  "bytes.Buffer": ["WriteString", "Write", "WriteByte", "String", "Bytes", "Len", "Reset", "Read"],
};

/* Go keywords filtered out of scope completions. */
export const GO_BLOCKLIST: ReadonlySet<string> = new Set([
  "break",
  "case",
  "chan",
  "const",
  "continue",
  "default",
  "defer",
  "else",
  "fallthrough",
  "for",
  "func",
  "go",
  "goto",
  "if",
  "import",
  "interface",
  "map",
  "package",
  "range",
  "return",
  "select",
  "struct",
  "switch",
  "type",
  "var",
  "true",
  "false",
  "nil",
  "iota",
]);
